export const CATEGORIES = [
    "Action",
    "Adventure",
    "Art",
    "Autobiography & Biographies",
    "Business",
    "Computer",
    "Contemporary",
    "Crime",
    "Detective",
    "Doctor Who",
    "Education",
    "Fantasy",
    "Gay",
    "General Fiction",
    "Historical Fiction",
    "History",
    "Horror",
    "Humor",
    "LGBT",
    "Lecture",
    "LitRPG",
    "Literature",
    "Military",
    "Misc. Non-fiction",
    "Mystery",
    "Other",
    "Paranormal",
    "Plays & Theater",
    "Poetry",
    "Political",
    "Postapocalyptic",
    "Radio Productions",
    "Romance",
    "SHTF",
    "Sci-Fi",
    "Science",
    "Self-help",
    "Spiritual",
    "Sports",
    "Suspense",
    "Thriller",
    "True Crime",
    "Tutorial",
    "Westerns",
    "Zombies"
];
