import React, { useState, useEffect } from 'react';
import { ABBSettings } from '@/shared/lib/types';
import { SettingsPageLayout } from '@/shared/ui/settings/SettingsPageLayout';
import { SettingsCard } from '@/shared/ui/settings/SettingsCard';
import { Save, BookHeadphones } from 'lucide-react';
import { useDebugId } from '@/shared/lib/hooks/useDebugId';

interface Props {
    settings: ABBSettings;
    updateSettings: (settings: ABBSettings) => void;
    embed?: boolean;
}

export const GeneralSettings: React.FC<Props> = ({ settings, updateSettings, embed }) => {
    const [previewTheme, setPreviewTheme] = useState<string>(settings.theme);
    const [trackers, setTrackers] = useState(settings.defaultTrackers.join('\n'));
    const [hasChanges, setHasChanges] = useState(false);

    // Debug IDs
    const trackersInputDebug = useDebugId('abb', 'settings', 'trackers-input');
    const saveBtnDebug = useDebugId('abb', 'settings', 'save-button');

    useEffect(() => {
        setPreviewTheme(settings.theme);
        setTrackers(settings.defaultTrackers.join('\n'));
        setHasChanges(false);
    }, [settings]);

    useEffect(() => {
        const themeChanged = previewTheme !== settings.theme;
        const trackersChanged = trackers !== settings.defaultTrackers.join('\n');
        setHasChanges(themeChanged || trackersChanged);
    }, [previewTheme, trackers, settings]);

    const saveAll = async () => {
        const newTrackers = trackers.split('\n').map(t => t.trim()).filter(Boolean);

        updateSettings({
            ...settings,
            theme: previewTheme,
            defaultTrackers: newTrackers
        });

        setHasChanges(false);
    };

    const Content = (
        <div className="space-y-8">
            <SettingsCard title="Magnet Link Trackers">
                <p className="text-sm text-text-secondary mb-4">
                    These trackers will be automatically added to every magnet link generated by the extension.
                </p>
                <textarea
                    className="w-full h-48 p-3 rounded-md bg-surface border border-border focus:ring-2 focus:ring-accent focus:outline-none font-mono text-sm text-text-primary transition-colors"
                    value={trackers}
                    onChange={(e) => setTrackers(e.target.value)}
                    placeholder="udp://tracker.opentrackr.org:1337/announce"
                    {...trackersInputDebug}
                />
            </SettingsCard>

            {/* Floating Save Button */}
            {hasChanges && (
                <div className="fixed bottom-8 right-8 z-50 animate-in fade-in slide-in-from-bottom-4 duration-300">
                    <button
                        onClick={saveAll}
                        className="bg-accent text-white px-6 py-3 rounded-full shadow-lg hover:bg-accent-hover transition-all transform hover:scale-105 font-bold flex items-center space-x-2 ring-2 ring-white dark:ring-gray-800"
                        {...saveBtnDebug}
                    >
                        <span>Save All Changes</span>
                        <Save className="w-5 h-5" />
                    </button>
                </div>
            )}
        </div>
    );

    if (embed) return Content;

    return (
        <SettingsPageLayout
            title="General Settings"
            description="Configure global extension behavior and appearance."
            icon={BookHeadphones}
        >
            {Content}
        </SettingsPageLayout>
    );
};
